site_name: Dashboard Template Database
site_url: https://qbolliet.github.io/dashboard-template-database/
repo_url: https://github.com/qbolliet/dashboard-template-database
site_dir: site
theme:
  name: material
  pygments_style: 'lovelace'
  logo: assets/logo.svg
  favicon: assets/logo.svg
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - navigation.sections
    #- navigation.expand
    - navigation.path
  palette:
   # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# extra_css:
#   - assets/stylesheets/extra.css

markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - markdown.extensions.sane_lists
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [src, docs/snippets]
          import:
          - https://docs.python.org/3/objects.inv
          - https://mkdocstrings.github.io/objects.inv
          - https://mkdocstrings.github.io/autorefs/objects.inv
          - https://mkdocstrings.github.io/griffe/objects.inv
          - https://python-markdown.github.io/objects.inv
          options:
            docstring_options:
              ignore_init_summary: true
            show_root_heading: true 
            merge_init_into_class: false 
            docstring_style: google
            docstring_section_style: table
            heading_level: 1
            filters: ["!^_"]
            inherited_members: true
            parameter_headings: true
            preload_modules: [mkdocstrings]
            relative_crossrefs: true
            scoped_crossrefs: true
            separate_signature: true
            show_bases: false
            show_inheritance_diagram: true
            show_root_full_path: false
            show_signature_annotations: true
            show_source: true
            show_symbol_type_heading: false
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
            unwrap_annotated: true

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML


nav:
  - Package description: index.md
  - API Documentation:
    - Builders :
      - DuckdbTablesBuilder : api/builders/DuckdbTablesBuilder.md
      - SchemaBuilder : api/builders/SchemaBuilder.md
    - Loaders :
      - Local :
        - Loader : api/loaders/local/Loader.md
      - S3 :
        - _S3Connection : api/loaders/s3/_S3Connection.md
        - S3Loader : api/loaders/s3/S3Loader.md
    - Utils :
      - _init_logger : api/utils/_init_logger.md